/*
 * Foundry USA Pool API
 *
 * The Foundry USA Pool API allows users to view data and perform actions using custom written software. To get started, please follow the instructions in the Authentication Test endpoint.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;

use crate::{apis::ResponseContent, models};
use super::{Error, configuration};

/// struct for passing parameters to the method [`get_balance_info`]
#[derive(Clone, Debug)]
pub struct GetBalanceInfoParams {
    /// Sub-Account name
    pub sub_account_name: String,
    /// OAuth2.0 access token. Not required if using API key.
    pub authorization: Option<String>,
    /// API key. Not required if using access token.
    pub x_api_key: Option<String>,
    /// Name of requested coin. Default value is BTC.
    pub coin: Option<String>
}

/// struct for passing parameters to the method [`get_earnings`]
#[derive(Clone, Debug)]
pub struct GetEarningsParams {
    /// Sub-Account name
    pub sub_account_name: String,
    /// API key. Not required if using access token.
    pub x_api_key: Option<String>,
    /// OAuth2.0 access token. Not required if using API key.
    pub authorization: Option<String>,
    /// Name of requested coin. Default value is BTC.
    pub coin: Option<String>,
    /// Start date inclusive, in unix epoch time (milliseconds). Default value is 0.
    pub start_date_unix_ms: Option<i64>,
    /// End date inclusive, in unix epoch time (milliseconds). Default value is current time.
    pub end_date_unix_ms: Option<i64>
}

/// struct for passing parameters to the method [`get_financial_stats_for_sub_accounts`]
#[derive(Clone, Debug)]
pub struct GetFinancialStatsForSubAccountsParams {
    /// OAuth2.0 access token.
    pub authorization: String,
    /// User ID is optional. Defaults to logged in user
    pub user_id: String,
    /// Name of requested coin.
    pub coin: Option<String>,
    /// Start date inclusive, in unix epoch time (milliseconds). Default value is 0. Specify UTC start of the day epoch time.
    pub start_date_unix_ms: Option<i64>,
    /// End date inclusive, in unix epoch time (milliseconds). Default value is current time.
    pub end_date_unix_ms: Option<i64>,
    /// List of group ids.
    pub group_ids_list: Option<Vec<i32>>
}

/// struct for passing parameters to the method [`get_transactions`]
#[derive(Clone, Debug)]
pub struct GetTransactionsParams {
    /// Sub-Account name
    pub sub_account_name: String,
    /// API key. Not required if using access token.
    pub x_api_key: Option<String>,
    /// OAuth2.0 access token. Not required if using API key.
    pub authorization: Option<String>,
    /// Name of requested coin. Default value is BTC.
    pub coin: Option<String>,
    /// Start date inclusive, in unix epoch time (milliseconds). Default value is 0.
    pub start_date_unix_ms: Option<i64>,
    /// End date inclusive, in unix epoch time (milliseconds). Default value is current time.
    pub end_date_unix_ms: Option<i64>
}


/// struct for typed errors of method [`get_balance_info`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetBalanceInfoError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_earnings`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetEarningsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_financial_stats_for_sub_accounts`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetFinancialStatsForSubAccountsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_transactions`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetTransactionsError {
    UnknownValue(serde_json::Value),
}


/// Get balance, total earned, total fees and total withdrawn amount for a requested sub-account. Requires authorized user or admin authentication.
pub async fn get_balance_info(configuration: &configuration::Configuration, params: GetBalanceInfoParams) -> Result<models::BalanceResponse, Error<GetBalanceInfoError>> {
    let local_var_configuration = configuration;

    // unbox the parameters
    let sub_account_name = params.sub_account_name;
    let authorization = params.authorization;
    let x_api_key = params.x_api_key;
    let coin = params.coin;


    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!("{}/balance/{subAccountName}", local_var_configuration.base_path, subAccountName=crate::apis::urlencode(sub_account_name));
    let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

    if let Some(ref local_var_str) = coin {
        local_var_req_builder = local_var_req_builder.query(&[("coin", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(local_var_param_value) = authorization {
        local_var_req_builder = local_var_req_builder.header("Authorization", local_var_param_value.to_string());
    }
    if let Some(local_var_param_value) = x_api_key {
        local_var_req_builder = local_var_req_builder.header("X-API-KEY", local_var_param_value.to_string());
    }

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content).map_err(Error::from)
    } else {
        let local_var_entity: Option<GetBalanceInfoError> = serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Err(Error::ResponseError(local_var_error))
    }
}

/// Get daily aggregated earnings for a requested sub-account. Requires authorized user or admin authentication.
pub async fn get_earnings(configuration: &configuration::Configuration, params: GetEarningsParams) -> Result<Vec<models::EarningResponse>, Error<GetEarningsError>> {
    let local_var_configuration = configuration;

    // unbox the parameters
    let sub_account_name = params.sub_account_name;
    let x_api_key = params.x_api_key;
    let authorization = params.authorization;
    let coin = params.coin;
    let start_date_unix_ms = params.start_date_unix_ms;
    let end_date_unix_ms = params.end_date_unix_ms;


    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!("{}/earnings/{subAccountName}", local_var_configuration.base_path, subAccountName=crate::apis::urlencode(sub_account_name));
    let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

    if let Some(ref local_var_str) = coin {
        local_var_req_builder = local_var_req_builder.query(&[("coin", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_str) = start_date_unix_ms {
        local_var_req_builder = local_var_req_builder.query(&[("startDateUnixMs", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_str) = end_date_unix_ms {
        local_var_req_builder = local_var_req_builder.query(&[("endDateUnixMs", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(local_var_param_value) = x_api_key {
        local_var_req_builder = local_var_req_builder.header("X-API-KEY", local_var_param_value.to_string());
    }
    if let Some(local_var_param_value) = authorization {
        local_var_req_builder = local_var_req_builder.header("Authorization", local_var_param_value.to_string());
    }

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content).map_err(Error::from)
    } else {
        let local_var_entity: Option<GetEarningsError> = serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Err(Error::ResponseError(local_var_error))
    }
}

/// Get financial stats and their total for sub-accounts associated with a user. User authentication required to see their own granted sub-accounts. Admin authentication with read permission required to see other users granted sub-accounts.
pub async fn get_financial_stats_for_sub_accounts(configuration: &configuration::Configuration, params: GetFinancialStatsForSubAccountsParams) -> Result<models::SubAccountsFinancialStatsResponse, Error<GetFinancialStatsForSubAccountsError>> {
    let local_var_configuration = configuration;

    // unbox the parameters
    let authorization = params.authorization;
    let user_id = params.user_id;
    let coin = params.coin;
    let start_date_unix_ms = params.start_date_unix_ms;
    let end_date_unix_ms = params.end_date_unix_ms;
    let group_ids_list = params.group_ids_list;


    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!("{}/financial_overview/{userId}", local_var_configuration.base_path, userId=crate::apis::urlencode(user_id));
    let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

    if let Some(ref local_var_str) = coin {
        local_var_req_builder = local_var_req_builder.query(&[("coin", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_str) = start_date_unix_ms {
        local_var_req_builder = local_var_req_builder.query(&[("startDateUnixMs", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_str) = end_date_unix_ms {
        local_var_req_builder = local_var_req_builder.query(&[("endDateUnixMs", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_str) = group_ids_list {
        local_var_req_builder = match "multi" {
            "multi" => local_var_req_builder.query(&local_var_str.into_iter().map(|p| ("groupIdsList".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => local_var_req_builder.query(&[("groupIdsList", &local_var_str.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    local_var_req_builder = local_var_req_builder.header("Authorization", authorization.to_string());

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content).map_err(Error::from)
    } else {
        let local_var_entity: Option<GetFinancialStatsForSubAccountsError> = serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Err(Error::ResponseError(local_var_error))
    }
}

/// Get transactions for a requested sub-account. Requires authorized user or admin authentication.
pub async fn get_transactions(configuration: &configuration::Configuration, params: GetTransactionsParams) -> Result<Vec<models::TransactionResponse>, Error<GetTransactionsError>> {
    let local_var_configuration = configuration;

    // unbox the parameters
    let sub_account_name = params.sub_account_name;
    let x_api_key = params.x_api_key;
    let authorization = params.authorization;
    let coin = params.coin;
    let start_date_unix_ms = params.start_date_unix_ms;
    let end_date_unix_ms = params.end_date_unix_ms;


    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!("{}/transactions/{subAccountName}", local_var_configuration.base_path, subAccountName=crate::apis::urlencode(sub_account_name));
    let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

    if let Some(ref local_var_str) = coin {
        local_var_req_builder = local_var_req_builder.query(&[("coin", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_str) = start_date_unix_ms {
        local_var_req_builder = local_var_req_builder.query(&[("startDateUnixMs", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_str) = end_date_unix_ms {
        local_var_req_builder = local_var_req_builder.query(&[("endDateUnixMs", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(local_var_param_value) = x_api_key {
        local_var_req_builder = local_var_req_builder.header("X-API-KEY", local_var_param_value.to_string());
    }
    if let Some(local_var_param_value) = authorization {
        local_var_req_builder = local_var_req_builder.header("Authorization", local_var_param_value.to_string());
    }

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content).map_err(Error::from)
    } else {
        let local_var_entity: Option<GetTransactionsError> = serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Err(Error::ResponseError(local_var_error))
    }
}

