/*
 * Foundry USA Pool API
 *
 * The Foundry USA Pool API allows users to view data and perform actions using custom written software. To get started, please follow the instructions in the Authentication Test endpoint.
 *
 * The version of the OpenAPI document: 6.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActivityLogResponseV2WithTotal {
    #[serde(rename = "activityLogResponses")]
    pub activity_log_responses: Vec<models::ActivityLogResponseV2>,
    #[serde(rename = "totalLogs")]
    pub total_logs: i64,
}

impl ActivityLogResponseV2WithTotal {
    pub fn new(
        activity_log_responses: Vec<models::ActivityLogResponseV2>,
        total_logs: i64,
    ) -> ActivityLogResponseV2WithTotal {
        ActivityLogResponseV2WithTotal {
            activity_log_responses,
            total_logs,
        }
    }
}
