/*
 * Foundry USA Pool API
 *
 * The Foundry USA Pool API allows users to view data and perform actions using custom written software. To get started, please follow the instructions in the Authentication Test endpoint.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AdminRole {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "roleName")]
    pub role_name: String,
    #[serde(rename = "adminRead")]
    pub admin_read: bool,
    #[serde(rename = "adminWrite")]
    pub admin_write: bool,
}

impl AdminRole {
    pub fn new(id: i32, role_name: String, admin_read: bool, admin_write: bool) -> AdminRole {
        AdminRole {
            id,
            role_name,
            admin_read,
            admin_write,
        }
    }
}

