/*
 * Foundry USA Pool API
 *
 * The Foundry USA Pool API allows users to view data and perform actions using custom written software. To get started, please follow the instructions in the Authentication Test endpoint.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BalanceResponse {
    #[serde(rename = "balance")]
    pub balance: f64,
    #[serde(rename = "totalEarned")]
    pub total_earned: f64,
    #[serde(rename = "totalFCMFees")]
    pub total_fcm_fees: f64,
    #[serde(rename = "totalDebits")]
    pub total_debits: f64,
    #[serde(rename = "totalFees")]
    pub total_fees: f64,
    #[serde(rename = "totalWithdrawn")]
    pub total_withdrawn: f64,
}

impl BalanceResponse {
    pub fn new(balance: f64, total_earned: f64, total_fcm_fees: f64, total_debits: f64, total_fees: f64, total_withdrawn: f64) -> BalanceResponse {
        BalanceResponse {
            balance,
            total_earned,
            total_fcm_fees,
            total_debits,
            total_fees,
            total_withdrawn,
        }
    }
}

