/*
 * Foundry USA Pool API
 *
 * The Foundry USA Pool API allows users to view data and perform actions using custom written software. To get started, please follow the instructions in the Authentication Test endpoint.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EarningResponse {
    #[serde(rename = "startTime")]
    pub start_time: String,
    #[serde(rename = "endTime")]
    pub end_time: String,
    #[serde(rename = "totalAmount")]
    pub total_amount: f64,
    #[serde(rename = "hashrate")]
    pub hashrate: i64,
    #[serde(rename = "ppsBaseAmount")]
    pub pps_base_amount: f64,
    #[serde(rename = "txFeeRewardAmount")]
    pub tx_fee_reward_amount: f64,
    #[serde(rename = "fppsRatePercent")]
    pub fpps_rate_percent: f64,
    #[serde(rename = "feeAmount")]
    pub fee_amount: f64,
    #[serde(rename = "feeRatePercent")]
    pub fee_rate_percent: f64,
}

impl EarningResponse {
    pub fn new(start_time: String, end_time: String, total_amount: f64, hashrate: i64, pps_base_amount: f64, tx_fee_reward_amount: f64, fpps_rate_percent: f64, fee_amount: f64, fee_rate_percent: f64) -> EarningResponse {
        EarningResponse {
            start_time,
            end_time,
            total_amount,
            hashrate,
            pps_base_amount,
            tx_fee_reward_amount,
            fpps_rate_percent,
            fee_amount,
            fee_rate_percent,
        }
    }
}

