/*
 * Foundry USA Pool API
 *
 * The Foundry USA Pool API allows users to view data and perform actions using custom written software. To get started, please follow the instructions in the Authentication Test endpoint.
 *
 * The version of the OpenAPI document: 6.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GrantedSubAccountListResponse {
    #[serde(rename = "groupName")]
    pub group_name: String,
    #[serde(rename = "subAccountNamesAndRoles")]
    pub sub_account_names_and_roles: Vec<models::SubAccountNameAndRole>,
}

impl GrantedSubAccountListResponse {
    pub fn new(
        group_name: String,
        sub_account_names_and_roles: Vec<models::SubAccountNameAndRole>,
    ) -> GrantedSubAccountListResponse {
        GrantedSubAccountListResponse {
            group_name,
            sub_account_names_and_roles,
        }
    }
}
