/*
 * Foundry USA Pool API
 *
 * The Foundry USA Pool API allows users to view data and perform actions using custom written software. To get started, please follow the instructions in the Authentication Test endpoint.
 *
 * The version of the OpenAPI document: 6.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Group {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "ppsFeeRate")]
    pub pps_fee_rate: f64,
    #[serde(rename = "approvalThreshold")]
    pub approval_threshold: i32,
}

impl Group {
    pub fn new(id: i32, name: String, pps_fee_rate: f64, approval_threshold: i32) -> Group {
        Group {
            id,
            name,
            pps_fee_rate,
            approval_threshold,
        }
    }
}
