/*
 * Foundry USA Pool API
 *
 * The Foundry USA Pool API allows users to view data and perform actions using custom written software. To get started, please follow the instructions in the Authentication Test endpoint.
 *
 * The version of the OpenAPI document: 6.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GroupThresholdUpdateResponse {
    #[serde(rename = "groupName")]
    pub group_name: String,
    #[serde(rename = "newApprovalThreshold")]
    pub new_approval_threshold: i32,
    #[serde(rename = "approvalRequestId", skip_serializing_if = "Option::is_none")]
    pub approval_request_id: Option<i32>,
    #[serde(rename = "isApprovalActionRequired")]
    pub is_approval_action_required: bool,
    #[serde(rename = "approvalsRequired", skip_serializing_if = "Option::is_none")]
    pub approvals_required: Option<i32>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(rename = "approvers", skip_serializing_if = "Option::is_none")]
    pub approvers: Option<String>,
    #[serde(
        rename = "approvalActionRequired",
        skip_serializing_if = "Option::is_none"
    )]
    pub approval_action_required: Option<bool>,
}

impl GroupThresholdUpdateResponse {
    pub fn new(
        group_name: String,
        new_approval_threshold: i32,
        is_approval_action_required: bool,
    ) -> GroupThresholdUpdateResponse {
        GroupThresholdUpdateResponse {
            group_name,
            new_approval_threshold,
            approval_request_id: None,
            is_approval_action_required,
            approvals_required: None,
            status: None,
            approvers: None,
            approval_action_required: None,
        }
    }
}
