/*
 * Foundry USA Pool API
 *
 * The Foundry USA Pool API allows users to view data and perform actions using custom written software. To get started, please follow the instructions in the Authentication Test endpoint.
 *
 * The version of the OpenAPI document: 6.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GroupWithUsersResponseV2 {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "users")]
    pub users: Vec<models::UserResponse>,
}

impl GroupWithUsersResponseV2 {
    pub fn new(name: String, users: Vec<models::UserResponse>) -> GroupWithUsersResponseV2 {
        GroupWithUsersResponseV2 {
            id: None,
            name,
            users,
        }
    }
}
