/*
 * Foundry USA Pool API
 *
 * The Foundry USA Pool API allows users to view data and perform actions using custom written software. To get started, please follow the instructions in the Authentication Test endpoint.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubAccountsFinancialStatsResponse {
    #[serde(rename = "subAccountFinancialStatsList")]
    pub sub_account_financial_stats_list: Vec<models::SubAccountFinancialStatsResponse>,
    #[serde(rename = "totalOfSubAccountStats")]
    pub total_of_sub_account_stats: Vec<models::TotalStatsForSubAccountGroup>,
}

impl SubAccountsFinancialStatsResponse {
    pub fn new(sub_account_financial_stats_list: Vec<models::SubAccountFinancialStatsResponse>, total_of_sub_account_stats: Vec<models::TotalStatsForSubAccountGroup>) -> SubAccountsFinancialStatsResponse {
        SubAccountsFinancialStatsResponse {
            sub_account_financial_stats_list,
            total_of_sub_account_stats,
        }
    }
}

