/*
 * Foundry USA Pool API
 *
 * The Foundry USA Pool API allows users to view data and perform actions using custom written software. To get started, please follow the instructions in the Authentication Test endpoint.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubAccountAccessRequest {
    #[serde(rename = "userSubAccountAccess")]
    pub user_sub_account_access: Vec<models::UserSubAccountAccessRequest>,
}

impl SubAccountAccessRequest {
    pub fn new(user_sub_account_access: Vec<models::UserSubAccountAccessRequest>) -> SubAccountAccessRequest {
        SubAccountAccessRequest {
            user_sub_account_access,
        }
    }
}

