/*
 * Foundry USA Pool API
 *
 * The Foundry USA Pool API allows users to view data and perform actions using custom written software. To get started, please follow the instructions in the Authentication Test endpoint.
 *
 * The version of the OpenAPI document: 6.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubAccountNameAndRole {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "role")]
    pub role: String,
}

impl SubAccountNameAndRole {
    pub fn new(name: String, role: String) -> SubAccountNameAndRole {
        SubAccountNameAndRole { name, role }
    }
}
