/*
 * Foundry USA Pool API
 *
 * The Foundry USA Pool API allows users to view data and perform actions using custom written software. To get started, please follow the instructions in the Authentication Test endpoint.
 *
 * The version of the OpenAPI document: 6.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubAccountStatsWithRoleResponse {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "activeWorkers")]
    pub active_workers: i32,
    #[serde(rename = "offline15MinWorkerCount")]
    pub offline15_min_worker_count: i32,
    #[serde(rename = "offline24HrWorkerCount")]
    pub offline24_hr_worker_count: i32,
    #[serde(rename = "hashrate5minAvg")]
    pub hashrate5min_avg: i64,
    #[serde(rename = "hashrate15minAvg")]
    pub hashrate15min_avg: i64,
    #[serde(rename = "stale15minAvg")]
    pub stale15min_avg: i64,
    #[serde(rename = "reject15minAvg")]
    pub reject15min_avg: i64,
    #[serde(rename = "hashrate1hrAvg")]
    pub hashrate1hr_avg: i64,
    #[serde(rename = "hashrate24hrAvg")]
    pub hashrate24hr_avg: i64,
    #[serde(rename = "stale1hrAvg")]
    pub stale1hr_avg: i64,
    #[serde(rename = "reject1hrAvg")]
    pub reject1hr_avg: i64,
    #[serde(rename = "lastShareTime")]
    pub last_share_time: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
    #[serde(rename = "role")]
    pub role: String,
    #[serde(rename = "subAccountUsers")]
    pub sub_account_users: Vec<models::UserSubAccountResponse>,
    #[serde(rename = "subAccountUsersPermission")]
    pub sub_account_users_permission: bool,
    #[serde(rename = "groupId")]
    pub group_id: i32,
    #[serde(rename = "groupName")]
    pub group_name: String,
    #[serde(rename = "fcmOptIn")]
    pub fcm_opt_in: bool,
    #[serde(rename = "isActive")]
    pub is_active: bool,
}

impl SubAccountStatsWithRoleResponse {
    pub fn new(
        name: String,
        active_workers: i32,
        offline15_min_worker_count: i32,
        offline24_hr_worker_count: i32,
        hashrate5min_avg: i64,
        hashrate15min_avg: i64,
        stale15min_avg: i64,
        reject15min_avg: i64,
        hashrate1hr_avg: i64,
        hashrate24hr_avg: i64,
        stale1hr_avg: i64,
        reject1hr_avg: i64,
        last_share_time: String,
        updated_at: String,
        role: String,
        sub_account_users: Vec<models::UserSubAccountResponse>,
        sub_account_users_permission: bool,
        group_id: i32,
        group_name: String,
        fcm_opt_in: bool,
        is_active: bool,
    ) -> SubAccountStatsWithRoleResponse {
        SubAccountStatsWithRoleResponse {
            name,
            active_workers,
            offline15_min_worker_count,
            offline24_hr_worker_count,
            hashrate5min_avg,
            hashrate15min_avg,
            stale15min_avg,
            reject15min_avg,
            hashrate1hr_avg,
            hashrate24hr_avg,
            stale1hr_avg,
            reject1hr_avg,
            last_share_time,
            updated_at,
            role,
            sub_account_users,
            sub_account_users_permission,
            group_id,
            group_name,
            fcm_opt_in,
            is_active,
        }
    }
}
