/*
 * Foundry USA Pool API
 *
 * The Foundry USA Pool API allows users to view data and perform actions using custom written software. To get started, please follow the instructions in the Authentication Test endpoint.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TagAlertResponse {
    #[serde(rename = "tagName")]
    pub tag_name: String,
    #[serde(rename = "alertId")]
    pub alert_id: i32,
    #[serde(rename = "hashrateThreshold")]
    pub hashrate_threshold: i64,
    #[serde(rename = "activeWorkersThreshold")]
    pub active_workers_threshold: i32,
    #[serde(rename = "emailList")]
    pub email_list: Vec<String>,
}

impl TagAlertResponse {
    pub fn new(tag_name: String, alert_id: i32, hashrate_threshold: i64, active_workers_threshold: i32, email_list: Vec<String>) -> TagAlertResponse {
        TagAlertResponse {
            tag_name,
            alert_id,
            hashrate_threshold,
            active_workers_threshold,
            email_list,
        }
    }
}

