/*
 * Foundry USA Pool API
 *
 * The Foundry USA Pool API allows users to view data and perform actions using custom written software. To get started, please follow the instructions in the Authentication Test endpoint.
 *
 * The version of the OpenAPI document: 6.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TagResponse {
    #[serde(rename = "tagId")]
    pub tag_id: i32,
    #[serde(rename = "tagName")]
    pub tag_name: String,
}

impl TagResponse {
    pub fn new(tag_id: i32, tag_name: String) -> TagResponse {
        TagResponse { tag_id, tag_name }
    }
}
