/*
 * Foundry USA Pool API
 *
 * The Foundry USA Pool API allows users to view data and perform actions using custom written software. To get started, please follow the instructions in the Authentication Test endpoint.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TagAlertsResponse {
    #[serde(rename = "tagAlerts")]
    pub tag_alerts: Vec<models::TagAlertResponse>,
}

impl TagAlertsResponse {
    pub fn new(tag_alerts: Vec<models::TagAlertResponse>) -> TagAlertsResponse {
        TagAlertsResponse {
            tag_alerts,
        }
    }
}

