/*
 * Foundry USA Pool API
 *
 * The Foundry USA Pool API allows users to view data and perform actions using custom written software. To get started, please follow the instructions in the Authentication Test endpoint.
 *
 * The version of the OpenAPI document: 6.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TotalStatsForSubAccountGroup {
    /// The day in which the stats were calculated.
    #[serde(rename = "statsDate")]
    pub stats_date: String,
    /// Total hashrate across subaccounts in the last 24 hours.
    #[serde(rename = "totalHashratePrevDay")]
    pub total_hashrate_prev_day: i64,
    /// Total PPS base amount in the last 24 hours.
    #[serde(rename = "totalPpsBaseAmount")]
    pub total_pps_base_amount: f64,
    /// Total tx fee reward amount in the last 24 hours.
    #[serde(rename = "totalTxFeeRewardAmount")]
    pub total_tx_fee_reward_amount: f64,
    /// Total fee amount in the last 24 hours.
    #[serde(rename = "totalFeeAmount")]
    pub total_fee_amount: f64,
    /// Total earned for group in the last 24 hours.
    #[serde(rename = "totalEarnedInDuration")]
    pub total_earned_in_duration: f64,
    /// Total fees paid in the last 24 hours.
    #[serde(rename = "totalFeesInDuration")]
    pub total_fees_in_duration: f64,
    /// Total withdrawn in the last 24 hours.
    #[serde(rename = "totalWithdrawnInDuration")]
    pub total_withdrawn_in_duration: f64,
    /// Total earned for group until the present time
    #[serde(rename = "totalEarnedToDate")]
    pub total_earned_to_date: f64,
    /// Total fees paid until the present time.
    #[serde(rename = "totalFeesToDate")]
    pub total_fees_to_date: f64,
    /// Total withdrawn until the present time.
    #[serde(rename = "totalWithdrawnToDate")]
    pub total_withdrawn_to_date: f64,
    /// Total balance until the present time.
    #[serde(rename = "balanceToDate")]
    pub balance_to_date: f64,
}

impl TotalStatsForSubAccountGroup {
    pub fn new(
        stats_date: String,
        total_hashrate_prev_day: i64,
        total_pps_base_amount: f64,
        total_tx_fee_reward_amount: f64,
        total_fee_amount: f64,
        total_earned_in_duration: f64,
        total_fees_in_duration: f64,
        total_withdrawn_in_duration: f64,
        total_earned_to_date: f64,
        total_fees_to_date: f64,
        total_withdrawn_to_date: f64,
        balance_to_date: f64,
    ) -> TotalStatsForSubAccountGroup {
        TotalStatsForSubAccountGroup {
            stats_date,
            total_hashrate_prev_day,
            total_pps_base_amount,
            total_tx_fee_reward_amount,
            total_fee_amount,
            total_earned_in_duration,
            total_fees_in_duration,
            total_withdrawn_in_duration,
            total_earned_to_date,
            total_fees_to_date,
            total_withdrawn_to_date,
            balance_to_date,
        }
    }
}
