/*
 * Foundry USA Pool API
 *
 * The Foundry USA Pool API allows users to view data and perform actions using custom written software. To get started, please follow the instructions in the Authentication Test endpoint.
 *
 * The version of the OpenAPI document: 6.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserGroupRequest {
    /// The name of the group
    #[serde(rename = "groupName")]
    pub group_name: String,
    /// Role of new user for that group. Valid values are \"owner\", \"accountant\" or \"technician\"
    #[serde(rename = "subaccountRoleName")]
    pub subaccount_role_name: String,
}

impl UserGroupRequest {
    pub fn new(group_name: String, subaccount_role_name: String) -> UserGroupRequest {
        UserGroupRequest {
            group_name,
            subaccount_role_name,
        }
    }
}
