/*
 * Foundry USA Pool API
 *
 * The Foundry USA Pool API allows users to view data and perform actions using custom written software. To get started, please follow the instructions in the Authentication Test endpoint.
 *
 * The version of the OpenAPI document: 6.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserSubAccountAccessRequest {
    #[serde(rename = "userId", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<i32>,
    #[serde(rename = "subAccountRole", skip_serializing_if = "Option::is_none")]
    pub sub_account_role: Option<String>,
}

impl UserSubAccountAccessRequest {
    pub fn new() -> UserSubAccountAccessRequest {
        UserSubAccountAccessRequest {
            user_id: None,
            sub_account_role: None,
        }
    }
}
