/*
 * Foundry USA Pool API
 *
 * The Foundry USA Pool API allows users to view data and perform actions using custom written software. To get started, please follow the instructions in the Authentication Test endpoint.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserGroup {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "group")]
    pub group: Box<models::Group>,
    #[serde(rename = "userRole")]
    pub user_role: Box<models::UserRole>,
    #[serde(rename = "defaultSubAccountRole")]
    pub default_sub_account_role: Box<models::UserSubAccountRole>,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
}

impl UserGroup {
    pub fn new(id: i32, group: models::Group, user_role: models::UserRole, default_sub_account_role: models::UserSubAccountRole, created_at: String, updated_at: String) -> UserGroup {
        UserGroup {
            id,
            group: Box::new(group),
            user_role: Box::new(user_role),
            default_sub_account_role: Box::new(default_sub_account_role),
            created_at,
            updated_at,
        }
    }
}

