/*
 * Foundry USA Pool API
 *
 * The Foundry USA Pool API allows users to view data and perform actions using custom written software. To get started, please follow the instructions in the Authentication Test endpoint.
 *
 * The version of the OpenAPI document: 6.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WalletsResponse {
    #[serde(rename = "walletList")]
    pub wallet_list: Vec<models::WalletResponse>,
}

impl WalletsResponse {
    pub fn new(wallet_list: Vec<models::WalletResponse>) -> WalletsResponse {
        WalletsResponse { wallet_list }
    }
}
