/*
 * Foundry USA Pool API
 *
 * The Foundry USA Pool API allows users to view data and perform actions using custom written software. To get started, please follow the instructions in the Authentication Test endpoint.
 *
 * The version of the OpenAPI document: 6.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WalletResponse {
    #[serde(rename = "address")]
    pub address: String,
    #[serde(rename = "label")]
    pub label: String,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "allocationPercent")]
    pub allocation_percent: f64,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "isAutoWithdraw")]
    pub is_auto_withdraw: bool,
    #[serde(rename = "subAccountWalletId", skip_serializing_if = "Option::is_none")]
    pub sub_account_wallet_id: Option<i32>,
    #[serde(rename = "approvalRequestId", skip_serializing_if = "Option::is_none")]
    pub approval_request_id: Option<i32>,
    #[serde(rename = "isApprovalActionRequired")]
    pub is_approval_action_required: bool,
    #[serde(rename = "approvalThreshold", skip_serializing_if = "Option::is_none")]
    pub approval_threshold: Option<i32>,
    #[serde(rename = "approvers", skip_serializing_if = "Option::is_none")]
    pub approvers: Option<String>,
}

impl WalletResponse {
    pub fn new(
        address: String,
        label: String,
        status: String,
        allocation_percent: f64,
        created_at: String,
        is_auto_withdraw: bool,
        is_approval_action_required: bool,
    ) -> WalletResponse {
        WalletResponse {
            address,
            label,
            status,
            allocation_percent,
            created_at,
            is_auto_withdraw,
            sub_account_wallet_id: None,
            approval_request_id: None,
            is_approval_action_required,
            approval_threshold: None,
            approvers: None,
        }
    }
}
