/*
 * Foundry USA Pool API
 *
 * The Foundry USA Pool API allows users to view data and perform actions using custom written software. To get started, please follow the instructions in the Authentication Test endpoint.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkerResponse {
    #[serde(rename = "workerId")]
    pub worker_id: String,
    #[serde(rename = "workerName")]
    pub worker_name: String,
    #[serde(rename = "hashrate_5m")]
    pub hashrate_5m: i64,
    #[serde(rename = "hashrate_15m")]
    pub hashrate_15m: i64,
    #[serde(rename = "stale_15m")]
    pub stale_15m: i64,
    #[serde(rename = "stale15mPercent")]
    pub stale15m_percent: f64,
    #[serde(rename = "reject_15m")]
    pub reject_15m: i64,
    #[serde(rename = "reject15mPercent")]
    pub reject15m_percent: f64,
    #[serde(rename = "rejectDetail_15m")]
    pub reject_detail_15m: String,
    #[serde(rename = "hashrate_1h")]
    pub hashrate_1h: i64,
    #[serde(rename = "stale_1h")]
    pub stale_1h: i64,
    #[serde(rename = "reject_1h")]
    pub reject_1h: i64,
    #[serde(rename = "rejectDetail_1h")]
    pub reject_detail_1h: String,
    #[serde(rename = "lastShareTime")]
    pub last_share_time: String,
    #[serde(rename = "updatedAt", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
    #[serde(rename = "tag")]
    pub tag: String,
}

impl WorkerResponse {
    pub fn new(worker_id: String, worker_name: String, hashrate_5m: i64, hashrate_15m: i64, stale_15m: i64, stale15m_percent: f64, reject_15m: i64, reject15m_percent: f64, reject_detail_15m: String, hashrate_1h: i64, stale_1h: i64, reject_1h: i64, reject_detail_1h: String, last_share_time: String, tag: String) -> WorkerResponse {
        WorkerResponse {
            worker_id,
            worker_name,
            hashrate_5m,
            hashrate_15m,
            stale_15m,
            stale15m_percent,
            reject_15m,
            reject15m_percent,
            reject_detail_15m,
            hashrate_1h,
            stale_1h,
            reject_1h,
            reject_detail_1h,
            last_share_time,
            updated_at: None,
            tag,
        }
    }
}

