/*
 * Foundry USA Pool API
 *
 * The Foundry USA Pool API allows users to view data and perform actions using custom written software. To get started, please follow the instructions in the Authentication Test endpoint.
 *
 * The version of the OpenAPI document: 6.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkersResponse {
    #[serde(rename = "workersList")]
    pub workers_list: Vec<models::WorkerResponse>,
    #[serde(rename = "totalWorkerCount")]
    pub total_worker_count: i64,
}

impl WorkersResponse {
    pub fn new(
        workers_list: Vec<models::WorkerResponse>,
        total_worker_count: i64,
    ) -> WorkersResponse {
        WorkersResponse {
            workers_list,
            total_worker_count,
        }
    }
}
